"""add_analysis_stabilization_fields

Revision ID: 6a3423994853
Revises: 9a65e39013c1
Create Date: 2026-07-22 18:50:54.572181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a3423994853'
down_revision: Union[str, None] = '9a65e39013c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analyses', sa.Column('missing_clauses', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('ai_explanation', sa.Text(), nullable=True))
    op.add_column('analyses', sa.Column('confidence_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analyses', 'confidence_score')
    op.drop_column('analyses', 'ai_explanation')
    op.drop_column('analyses', 'missing_clauses')
    # ### end Alembic commands ###
