"""add_source_fields_to_documents

Revision ID: 9a65e39013c1
Revises: ca0ae8d2e663
Create Date: 2026-07-22 18:14:35.827540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a65e39013c1'
down_revision: Union[str, None] = 'ca0ae8d2e663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('source_type', sa.String(length=50), server_default='PDF', nullable=False))
    op.add_column('documents', sa.Column('source_url', sa.String(length=2048), nullable=True))
    op.create_index(op.f('ix_documents_source_type'), 'documents', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_source_type'), table_name='documents')
    op.drop_column('documents', 'source_url')
    op.drop_column('documents', 'source_type')
    # ### end Alembic commands ###
