"""extend documents table columns

Revision ID: fc260e149cee
Revises: bc31afda37bb
Create Date: 2026-07-21 14:38:18.094885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc260e149cee'
down_revision: Union[str, None] = 'bc31afda37bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('processing_status', sa.String(length=50), nullable=False))
    op.add_column('documents', sa.Column('text_extracted', sa.Boolean(), nullable=False))
    op.add_column('documents', sa.Column('extracted_text', sa.Text(), nullable=True))
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('word_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('processing_started_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('processing_completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'processing_completed_at')
    op.drop_column('documents', 'processing_started_at')
    op.drop_column('documents', 'word_count')
    op.drop_column('documents', 'page_count')
    op.drop_column('documents', 'extracted_text')
    op.drop_column('documents', 'text_extracted')
    op.drop_column('documents', 'processing_status')
    # ### end Alembic commands ###
